#!/usr/bin/env bash
# 02_train_snap.sh — Train a SNAP HMM for S. solidus.
#
# Uses the same training gene set generated by 01_train_augustus.sh, converted
# to ZFF (SNAP's native annotation format).
# Requires: SNAP (fathom, forge, hmm-assembler.pl), maker (maker2zff or gff3_merge).
set -euo pipefail
source "$(dirname "$0")/../config.sh"
setup_logging

TRAIN_DIR="${OUTDIR}/training/snap"
AUG_TRAIN_DIR="${OUTDIR}/training/augustus"
MASKED_GENOME="${OUTDIR}/repeats/$(basename "${GENOME}").masked"
WORK_DIR="${TMPDIR_BASE}/snap"
mkdir -p "${TRAIN_DIR}" "${WORK_DIR}"

TRAINING_GFF="${AUG_TRAIN_DIR}/training_genes.gff"
if [[ ! -f "${TRAINING_GFF}" ]]; then
    echo "ERROR: Training GFF not found: ${TRAINING_GFF}"
    echo "Run 01_train_augustus.sh first."
    exit 1
fi

cd "${WORK_DIR}"

# ── 1. Convert training GFF to ZFF format ────────────────────────────────────
echo "=== Converting training genes to ZFF ==="
maker2zff -n "${TRAINING_GFF}" 2>/dev/null \
    || gff3_to_zff.pl "${TRAINING_GFF}" "${MASKED_GENOME}" > genome.ann

if [[ ! -f genome.dna ]]; then
    ln -sf "${MASKED_GENOME}" genome.dna
fi

# ── 2. Validate and categorise training genes ────────────────────────────────
echo "=== Running fathom ==="
fathom genome.ann genome.dna -categorize 1000
fathom uni.ann uni.dna -export 1000 -plus

# ── 3. Build signal and content models ───────────────────────────────────────
echo "=== Running forge ==="
cd export
forge ../uni.ann ../uni.dna
cd ..

# ── 4. Assemble the HMM ─────────────────────────────────────────────────────
echo "=== Assembling SNAP HMM ==="
hmm-assembler.pl "${GENOME_LABEL}" export > "${TRAIN_DIR}/${GENOME_LABEL}.hmm"

echo "=== SNAP training complete ==="
echo "HMM file: ${TRAIN_DIR}/${GENOME_LABEL}.hmm"
